site_name: M3ragon`s Küche
site_url: https://m3ragon.github.io/material/
nav:
    - Home: index.md
    - Blog: blog.md
    - Kitchen:
      - cooking/index.md
      - Vorspeisen: 
        - cooking/appetizers/index.md
        - Räucherlachs mit Ciabatta: cooking/appetizers/SmokedSalmonWithCiabatta.md
        - Feta-Quiche mit Spinat: cooking/appetizers/FetaquicheWithSpinachBaconAndGarlic.md
      - Hauptgericht:
        - cooking/main_course/index.md
        - PLACEHOLDER: cooking/dessert/MaronenTiramisu.md
      - Desserts:
        - cooking/dessert/index.md
        - Maronen Tiramisu: cooking/dessert/MaronenTiramisu.md
        - Schokoladen Soufflé: cooking/dessert/SchokoladenSouffleMitTonkabohne.md
      - Beilagen:
        - cooking/supplement/index.md
        - Gratin: cooking/supplement/gratin.md
      - Diverse:
        - cooking/etc/index.md
        - Basilikum-Pesto: cooking/etc/BasilikumPesto.md
    - About: about.md
    - more:
      - more/index.md
      - A3Survival:
        - more/wiki_a3s/index.md
        - Weapons: more/wiki_a3s/weapons.md
        - Consumables: more/wiki_a3s/consumables.md
      - DayZServer: 
        - more/dayzserver/index.md
        - Regeln (DE): more/dayzserver/rules_de.md
        - Rules (EN): more/dayzserver/rules_en.md
        - Base Building: more/dayzserver/baseraiding.md
        - Territories: more/dayzserver/territories.md
      - Test:
        - more/TestSite/index.md
        - nav: more/TestSite/index.md

theme:
  name: material
  features:
    - content.code.annotate
    - content.tabs.link
    - navigation.tabs
    - navigation.top
  logo: asset/img/logo.svg
  favicon: asset/img/logo.svg
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - search
  - minify:
      minify_html: true
      minify_js: false
      minify_css: false
      htmlmin_opts:
          remove_comments: true

markdown_extensions:
  - tables
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
  - abbr
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
  - toc:
      permalink: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - footnotes

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - asset/javascripts/tablesort.js

extra_css:
  - asset/stylesheets/extra.css

extra:
  homepage: https://m3ragon.github.io/material/
