site_name: A3Survival
#site_url: https://example.com/
nav:
    - Home: index.md
    - About: about.md
    - RulesDE: rules_de.md
    - RulesEN: rules_en.md
    - Base Building: baseraiding.md
    - Territories: territories.md
theme:
  name: material

plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true
      js_files:
      css_files:
