site_name: A3Survival
#site_url: https://example.com/
nav:
    - Home: index.md
    - About: about.md
    - RulesDE: rules_de.md
    - RulesEN: rules_en.md
    - Base Building: baseraiding.md
    - Territories: territories.md
theme:
  name: material
  features:
    - content.code.annotate
    - content.tabs.link


plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true
      js_files:
      css_files:

markdown_extensions:
  - tables
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 


extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tablesort.js
