site_name: Site of M3ragon
site_url: https://m3ragon.github.io/material/
nav:
    - Home: index.md
    - Kitchen:
      - cooking/index.md
      - Appetizers: 
        - cooking/appetizers/index.md
        - Räucherlach mit Ciabatta: cooking/appetizers/SmokedSalmonWithCiabatta.md
        - Feta-Quiche mit Spinat: cooking/appetizers/FetaquicheWithSpinachBaconAndGarlic.md
    - A3Survival:
      - wiki_a3s/index.md
      - Weapons: wiki_a3s/weapons.md
      - Consumables: wiki_a3s/consumables.md
    - DayZServer: 
      - dayzserver/index.md
      - Regeln (DE): dayzserver/rules_de.md
      - Rules (EN): dayzserver/rules_en.md
      - Base Building: dayzserver/baseraiding.md
      - Territories: dayzserver/territories.md
    - Test:
      - TestSite/index.md
      - nav: TestSite/index.md
    - About: about.md

theme:
  name: material
  features:
    - content.code.annotate
    - content.tabs.link
    - navigation.indexes
    - navigation.top
  logo: asset/img/logo.svg
  favicon: asset/img/logo.svg
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: Dark-Green
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - search
  - minify:
      minify_html: true
      minify_js: false
      minify_css: false
      htmlmin_opts:
          remove_comments: true

markdown_extensions:
  - tables
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
  - abbr
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
  - toc:
      permalink: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - footnotes

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - asset/javascripts/tablesort.js

extra_css:
  - asset/stylesheets/extra.css

extra:
  homepage: https://m3ragon.github.io/material/
